.gitignore, src/main/java/dnd/donworry/DonworryApplication.java, src/main/java/dnd/donworry/domain/BaseEntity.java, src/main/java/dnd/donworry/domain/Comment.java, src/main/java/dnd/donworry/domain/CommentLike.java, src/main/java/dnd/donworry/domain/OptionImage.java, src/main/java/dnd/donworry/domain/Selection.java, src/main/java/dnd/donworry/domain/User.java, src/main/java/dnd/donworry/domain/UserVote.java, src/main/java/dnd/donworry/domain/Vote.java, src/main/java/dnd/donworry/domain/VoteLike.java
원할한 개발 진행을 위해 엔티티간의 연관관계 매핑을 모두 진행했습니다.
JPA 매핑 코드를 작성하며 적용한 규칙은 다음과 같습니다.
1. 양방향 매핑은 진행하지 않는다.
2. JoinColumn은 생략할 수 있으면 생략한다.
3. 컬럼명은 따로 작성하지 않는다.
4. 복합, 식별 외래키는 사용하지 않는다.
- S3와 RDS를 연결하지 않았기 때문에 서버가 다운됩니다.
- 다음 머지 진행 시 환경 세팅을 마무리하면 서버가 제대로 동작하게 됩니다.
close #22
=> [FEAT] 연관관계 매핑

.gitignore, build.gradle, src/main/java/dnd/donworry/config/S3Config.java, src/main/java/dnd/donworry/core/factory/YamlPropertySourceFactory.java, src/main/java/dnd/donworry/core/manager/AWSFileManager.java, src/main/java/dnd/donworry/core/manager/FileManager.java, src/main/resources/application.yml
- AWS 저장소 연결에 필요한 라이브러리를 설정했습니다.
- AWS 저장소 연결에 필요한 yml을 생성했습니다.
- 기본 yml과 깃에 올라가지 않을 dev, prod yml을 분리하여 개발 환경과 배포 환경을 구분했습니다.
- 클래스 별로 yml을 적용할 수 있도록 yml 팩토리를 생성했습니다.
close #26
=> [SET]  yml 분리 및 AWS 저장소 연결

src/main/java/dnd/donworry/domain/constants/ErrorCode.java, src/main/java/dnd/donworry/domain/constants/ResResult.java, src/main/java/dnd/donworry/domain/constants/ResponseCode.java
[FEAT] ResponseCode , ErrorCode 세팅
=> ✨ ResponseCode , errorCode setting

src/main/java/dnd/donworry/domain/constants/ErrorCode.java
빌더에 삭제된 errorCode가 포함되어 빌드가 되지 않던 버그를 수정했습니다.
=> [BUGFIX] ErrorCode 빌드 에러 수정

.github/workflows/gradle.yml
=> 🚀 Workflow 파일 수정

src/main/java/dnd/donworry/controller/VoteController.java, src/main/java/dnd/donworry/util/MultipartJackson2HttpMessageConverter.java
스웨거에서 투표 생성 API 호출 시 발생하는 오류를 해결하는 클래스 설정 파일을 추가합니다.
현재 투표 생성 API에서 외래키 제약 에러로 인해 500 Response가 반환되는데 이는 User Class 연동이 마무리되면 해결될 예정입니다.
=> [FIX] Multipart octet 에러 수정

src/main/java/dnd/donworry/domain/constants/ErrorCode.java, src/main/java/dnd/donworry/service/impl/UserServiceImpl.java
[REFACTOR] 유저 닉네임 변경 기능에서 customException의 errorCode를 수정하였습니다.
=> ♻️유저 닉네임 변경 _customException 수정

src/main/java/dnd/donworry/domain/constants/ErrorCode.java, src/main/java/dnd/donworry/domain/constants/PreQuestion_AGE.java, src/main/java/dnd/donworry/domain/constants/PreQuestion_Gender.java, src/main/java/dnd/donworry/domain/dto/test/TestRequestDto.java, src/main/java/dnd/donworry/domain/dto/test/TestResponseDto.java, src/main/java/dnd/donworry/domain/entity/TestResult.java
테스트 시작 전 사전질문에 나이와 성별을 저장하는 컬럼을 추가했습니다.
해당 데이터는 테스트 결과 테이블에 다른 데이터와 함께 저장되며 프론트에서 사용하지 않더라도 반환됩니다.
나이는 "10대 미만", "20대", "30대", "40대 이상"으로 나뉘며 성별은 "남자","여지"로 나뉩니다.
=> [FEAT] 사전질문 컬럼 추가

src/main/java/dnd/donworry/controller/CommentController.java, src/main/java/dnd/donworry/domain/constants/ErrorCode.java, src/main/java/dnd/donworry/domain/constants/ResponseCode.java, src/main/java/dnd/donworry/domain/dto/comment/CommentRequestDto.java, src/main/java/dnd/donworry/domain/dto/comment/CommentResponseDto.java, src/main/java/dnd/donworry/domain/entity/Comment.java, src/main/java/dnd/donworry/repository/CommentRepository.java, src/main/java/dnd/donworry/service/CommentService.java, src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java, src/test/java/dnd/donworry/service/impl/CommentServiceImplTest.java
댓글 생성, 수정 ,삭제 API 개발을 하고 Swagger 문서 정리를 했습니다.
생성과 수정에 관한 테스트 코드 작성했습니다.
=> [FEAT] 댓글 생성, 수정, 삭제 API 구현

src/main/java/dnd/donworry/domain/constants/ErrorCode.java
=> [BUGFIX]  예상치 않은 세미클론이 삽입된 구문오류 수정

src/main/java/dnd/donworry/config/SecurityConfig.java, src/main/java/dnd/donworry/controller/OauthController.java, src/main/java/dnd/donworry/controller/UserController.java, src/main/java/dnd/donworry/service/OauthService.java, src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java, src/main/java/dnd/donworry/service/impl/UserServiceImpl.java
스웨거에서 사용할 수 있는 유저를 생성하고 바로 로그인할 수 있는 기능을 구현했습니다.
스웨거에서 사용할 수 있는 유저를 생성하고 바로 로그인할 수 있는 기능을 구현했습니다.
=> [FEAT] 스웨거 유저 생성 기능 구현

src/main/java/dnd/donworry/config/SecurityConfig.java, src/main/java/dnd/donworry/controller/TestController.java, src/main/java/dnd/donworry/domain/dto/test/TestRequestDto.java, src/main/java/dnd/donworry/domain/dto/test/TestResponseDto.java, src/main/java/dnd/donworry/domain/entity/TestResult.java, src/main/java/dnd/donworry/service/TestService.java, src/main/java/dnd/donworry/service/impl/TestServiceImpl.java
회원과 비회원의 테스트 결과 생성 로직을 분리했습니다.
회원은 테스트 결과를 저장하고 비회원은 저장하지 않습니다.
=> [REFACTOR] 테스트 결과 API 분리

src/main/java/dnd/donworry/controller/VoteController.java, src/main/java/dnd/donworry/domain/constants/ResponseCode.java, src/main/java/dnd/donworry/domain/dto/selection/SelectionRequestDto.java, src/main/java/dnd/donworry/domain/dto/selection/SelectionResponseDto.java, src/main/java/dnd/donworry/domain/dto/vote/VoteRequestDto.java, src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java, src/main/java/dnd/donworry/domain/dto/vote/VoteUpdateDto.java, src/main/java/dnd/donworry/domain/entity/Selection.java, src/main/java/dnd/donworry/domain/entity/Vote.java, src/main/java/dnd/donworry/service/VoteService.java, src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
이미지가 없는 경우, 있는 경우를 통합한 API를 구현했습니다.
Swagger에서는 List에 null을 입력하지 못해 테스트가 불가능합니다.
커밋 목록에는 생성만 적혀있지만 읽기, 수정, 삭제 API를 모두 구현했습니다.
전체 목록 조회에 페이징은 아직 적용되지 않았습니다.
=> [FEAT] 투표 CRUD API 구현

src/main/java/dnd/donworry/domain/dto/vote/VoteRequestDto.java, src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java, src/main/java/dnd/donworry/domain/entity/Vote.java
기존의 LocalDateTime으로 주고 받던 마감일 형식을 LocalDate로 변경하여 '2024-02-18'과 같은 형식으로 주고 받습니다.
=> [REFACTOR] 마감일 형식 변경

src/main/java/dnd/donworry/config/SecurityConfig.java
프론트에서 cors를 사용할 수 있게 setting을 하였습니다.
```
@Bean
public CorsConfigurationSource corsConfigurationSource() {
CorsConfiguration corsConfiguration = new CorsConfiguration();
corsConfiguration.addAllowedHeader("*");
corsConfiguration.addAllowedMethod("*");
corsConfiguration.setAllowedMethods(Collections.singletonList("*"));
corsConfiguration.setAllowCredentials(true);
corsConfiguration.setAllowedOriginPatterns(Collections.singletonList("*"));
corsConfiguration.addAllowedHeader("http://localhost:3000");
corsConfiguration.addAllowedHeader("https://dontworry-3th.vercel.app");
UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
source.registerCorsConfiguration("/**", corsConfiguration);
return source;
}
```
=> [FEAT] CORS setting

src/main/java/dnd/donworry/domain/constants/ErrorCode.java, src/main/java/dnd/donworry/domain/constants/RANK.java, src/main/java/dnd/donworry/domain/dto/test/TestResponseDto.java, src/main/java/dnd/donworry/domain/entity/TestResult.java, src/main/java/dnd/donworry/manager/TestManager.java, src/main/java/dnd/donworry/service/TestService.java, src/main/java/dnd/donworry/service/impl/TestServiceImpl.java
데이터베이스에 저장되는 테스트 결과에 대한 ID 컬럼이 추가되었습니다.
하지만 비회원인 경우 테스트 결과가 데이터베이스에 저장되지 않기 떄문에 ID값이 반환되지 않습니다. 만약 백그라운드로 테스트 결과가 저장된다면 그 후로는 ID값이 반환됩니다.
테스트 결과 페이지에 표시될 이미지와 이미지 제목, 문구, 온도를 추가했습니다.
=> [FEAT] 투표 결과 페이지 수정

src/main/java/dnd/donworry/config/SecurityConfig.java, src/main/java/dnd/donworry/jwt/JwtFilter.java
=> [BUGFIX]  Cors 미작동으로 인한 재설정

src/main/java/dnd/donworry/config/WebMvcConfig.java
=> [BUGFIX] Cors 미작동으로 인한 재설정

src/main/java/dnd/donworry/config/SecurityConfig.java
=> 🚀 Cors 미작동으로 인한 재설정

src/main/java/dnd/donworry/service/impl/KakaoOauthServiceImpl.java
KakaoOauthServiceImpl 필요 없는 세미클론 제거하였습니다
=> [REFACTOR] KakaoOauthServiceImpl 필요 없는 세미클론 제거

src/main/java/dnd/donworry/config/SecurityConfig.java
/login/oauth2/code/kakao/** -> /login/oauth2/code/kakao 로 변경
=> [REFACTOR]securityConfig login url 수정

src/main/java/dnd/donworry/service/impl/KakaoOauthServiceImpl.java, src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java
=> [REFACTOR]  Client-Secret 추가

src/main/java/dnd/donworry/service/impl/KakaoOauthServiceImpl.java
KakaoOauthServiceImpl 진행 척도를 확인하기 위해 log를 추가하였습니다.
=> [REFACTOR] KakaoOauthServiceImpl log 추가

src/main/java/dnd/donworry/config/JwtConfig.java
기존 너무 짧게 잡혀 있던 토큰 유효시간을 access 2시간, refresh 2주로 변경하였습니다.
=> [REFACTOR]  access,refreshToken - exp 변경

src/main/java/dnd/donworry/config/CorsConfig.java, src/main/java/dnd/donworry/config/SecurityConfig.java
=>  [BUGFIX] cors setting 변경

src/main/java/dnd/donworry/config/SecurityConfig.java
/api/v1/vote/all 은 로그인이 필요없도록 security 에서 제외
=> ♻️  Spring Security permitAll() 목록 수정

src/main/java/dnd/donworry/service/impl/KakaoOauthServiceImpl.java
형용사 100개 부사 100개 명사100개 숫자 10000개 중 하나의 조합으로 랜덤한 닉네임 생성
=> [FEAT] 회원가입 시 닉네임 랜덤하게 추가

src/main/java/dnd/donworry/domain/entity/Vote.java, src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
=> [FEAT] 조회수 증가 기능 구현

src/main/java/dnd/donworry/controller/OauthController.java, src/main/java/dnd/donworry/domain/dto/user/LoginResponseDto.java, src/main/java/dnd/donworry/service/OauthService.java, src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java
기존 accessToken과 refreshToken만 반환했던 loginReponseDto에 nickname 필드를 추가해 함께 반환합니다.
`
{"code":"200","message":"로그인에 성공했습니다","data":{"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrc3dsc2doQG5hdmVyLmNvbSIsImV4cCI6MTcwODUzNTI1N30.NeZokItoaSjOeMpVLsLt0-OqmExYQDEtkdVQa8PXtY4","refreshToken":"eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDk3Mzc2NTd9.hH7usFJp1lmqcm_C1OJl4gXB5eb5730AlMCev5uHKRg","nickname":"편안하게건장한미래@8197"}}`
=> [REFACTOR]login 시 토큰과 함께 닉네임도 반환

src/main/java/dnd/donworry/jwt/JwtFilter.java
엑세스 토큰이 없고 , 리프레쉬 토큰만 가지고 있는 상황에서만 reissue하게 수정하였습니다.
=> [BUGFIX] 새로고침 시 토큰값이 매번 바뀌던 버그 수정

src/main/java/dnd/donworry/util/CookieUtil.java
=> [REFACTOR] cookie delete시 setSecure(true) 추가

src/main/java/dnd/donworry/controller/CommentController.java, src/main/java/dnd/donworry/domain/constants/Category.java, src/main/java/dnd/donworry/domain/constants/ErrorCode.java, src/main/java/dnd/donworry/domain/constants/ResponseCode.java, src/main/java/dnd/donworry/domain/dto/comment/CommentResponseDto.java, src/main/java/dnd/donworry/domain/dto/comment/CommentResponseReadDto.java, src/main/java/dnd/donworry/domain/dto/user/LoginResponseDto.java, src/main/java/dnd/donworry/repository/CommentLikeRepository.java, src/main/java/dnd/donworry/repository/CommentRepository.java, src/main/java/dnd/donworry/repository/custom/CommentRepositoryCustom.java, src/main/java/dnd/donworry/repository/impl/CommentRepositoryImpl.java, src/main/java/dnd/donworry/service/CommentService.java, src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
=> [FEAT] comment 페이징 ,공감 기능 구현

src/main/java/dnd/donworry/util/CookieUtil.java
=> [BUGFIX]로그아웃 수정

src/main/java/dnd/donworry/controller/CommentController.java, src/main/java/dnd/donworry/controller/OauthController.java, src/main/java/dnd/donworry/controller/TestController.java, src/main/java/dnd/donworry/controller/UserController.java, src/main/java/dnd/donworry/controller/UserVoteController.java, src/main/java/dnd/donworry/controller/VoteController.java, src/main/java/dnd/donworry/domain/constants/ErrorCode.java, src/main/java/dnd/donworry/domain/constants/ResponseCode.java, src/main/java/dnd/donworry/domain/entity/Vote.java, src/main/java/dnd/donworry/exception/ExceptionHandleFilter.java, src/main/java/dnd/donworry/exception/GlobalExceptionHandler.java, src/main/java/dnd/donworry/repository/impl/VoteRepositoryImpl.java
=> [BUGFIX] 로그아웃 수정

src/main/java/dnd/donworry/controller/CommentController.java
=> :bug: 로그아웃 수정

src/main/java/dnd/donworry/domain/dto/user/LoginResponseDto.java
=> [REFACTOR] kakao.yml secrets update

src/main/java/dnd/donworry/controller/TestController.java
=> [FEAT] 테스트 결과 API 수정

src/main/java/dnd/donworry/config/SecurityConfig.java, src/main/java/dnd/donworry/jwt/JwtFilter.java, src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java, src/main/java/dnd/donworry/service/impl/UserServiceImpl.java
refreshToken의 만료 시간이 잘못 설정됨에 따라 action의 secrets로 파일을 수정하고 redis에 잘못 기입된 유효기간도 수정하였습니다
=>  [BUGFIX] refreshToken의 만료 시간이 잘못 설정됨에 따라 코드 수정

src/main/java/dnd/donworry/controller/VoteController.java, src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDtoWithSelection.java, src/main/java/dnd/donworry/domain/entity/OptionImage.java, src/main/java/dnd/donworry/domain/entity/Selection.java, src/main/java/dnd/donworry/domain/entity/Vote.java, src/main/java/dnd/donworry/repository/custom/VoteRepositoryCustom.java, src/main/java/dnd/donworry/repository/impl/VoteRepositoryImpl.java, src/main/java/dnd/donworry/service/VoteService.java, src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
=> [BUGFIX]  테스트 결과 API N+1 해결

src/main/java/dnd/donworry/domain/entity/Vote.java, src/main/java/dnd/donworry/service/impl/UserVoteServiceImpl.java
투표에 참여하면 참여수가 증가하는 기능을 구현했습니다.
=> [FEAT] 투표 참여수 증가 기능 구현

src/main/java/dnd/donworry/domain/entity/Selection.java, src/main/java/dnd/donworry/service/impl/UserVoteServiceImpl.java
=> [BUGFIX] 선택지 카운트 증가 구현

src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
=> [REFACTOR] 퍼센트 오류 수정

src/main/java/dnd/donworry/controller/VoteController.java, src/main/java/dnd/donworry/domain/dto/selection/SelectionResponseDto.java
=> [BUGFIX] 투표 이미지 에러 수정

src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java, src/main/java/dnd/donworry/domain/entity/Vote.java, src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
투표 엔티티에 댓글 카운터 필드 추가
투표 response에 댓글 카운터 필드 추가
댓글 생성, 삭제 시 투표의 댓글 카운터 증감
=>  [FEAT]  투표 response에 댓글 개수 추가

src/main/java/dnd/donworry/controller/CommentController.java, src/main/java/dnd/donworry/domain/dto/comment/CommentPagingDto.java, src/main/java/dnd/donworry/domain/dto/comment/Pages.java, src/main/java/dnd/donworry/repository/custom/CommentRepositoryCustom.java, src/main/java/dnd/donworry/repository/impl/CommentRepositoryImpl.java, src/main/java/dnd/donworry/service/CommentService.java, src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
기존 no Offset 방식 -> Offset방식으로 변경
=> [REFACTOR] 댓글 페이징 방식 변경 

src/main/java/dnd/donworry/controller/VoteController.java, src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java, src/main/java/dnd/donworry/domain/entity/Vote.java, src/main/java/dnd/donworry/domain/entity/VoteLike.java, src/main/java/dnd/donworry/repository/VoteLikeRepository.java, src/main/java/dnd/donworry/repository/custom/VoteLikeRepositoryCustom.java, src/main/java/dnd/donworry/repository/impl/VoteLikeRepositoryImpl.java, src/main/java/dnd/donworry/service/VoteService.java, src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
투표 공감 기능을 구현하고 공감 수 컬럼을 추가했습니다.
베스트 투표의 경우에는 공감에 대한 표시 여부가 불필요하기에 false로 고정했습니다.
=> [FEAT] 투표 공감 기능 구현

src/main/java/dnd/donworry/domain/dto/comment/Pages.java
1.getTotalPages ->totalPages
2.getTotalElements -> totalElements
3.getNumber -> currentPage
으로 변수 명 변경
=> [REFACTOR]  Pages 클래스 변수 명 변경

src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
투표 공감을 취소한 경우 해당 내용을 컬럼에 반영합니다.
=> [BUGFIX]  공감 취소 반영

src/main/java/dnd/donworry/controller/VoteController.java, src/main/java/dnd/donworry/domain/dto/comment/Pages.java, src/main/java/dnd/donworry/domain/dto/vote/VotePagingDto.java, src/main/java/dnd/donworry/repository/custom/VoteRepositoryCustom.java, src/main/java/dnd/donworry/repository/impl/VoteRepositoryImpl.java, src/main/java/dnd/donworry/service/VoteService.java, src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
=> [FEAT] 투표 검색 API 구현

src/main/java/dnd/donworry/controller/CommentController.java, src/main/java/dnd/donworry/repository/custom/CommentRepositoryCustom.java, src/main/java/dnd/donworry/repository/impl/CommentRepositoryImpl.java, src/main/java/dnd/donworry/service/CommentService.java, src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
=> [FEAT] 댓글 전체 조회 API 개발

src/main/java/dnd/donworry/config/SecurityConfig.java
spring security filter에서 제외시켜 비 로그인 유저도 검색 기능을 사용할 수 있게 한다
=>  [REFACTOR]  투표 검색 기능 비 로그인 유저도 사용 가능 하게 security config 설정에 추가

src/main/java/dnd/donworry/domain/entity/Comment.java, src/main/java/dnd/donworry/repository/impl/CommentRepositoryImpl.java, src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
comment의 updateLike 시 likes 필드 값이 음수가 된 다면 0으로 고정하는 로직 추가
=> [BUGFIX] 댓글 공감 취소 시 카운터가 음수가 되는 버그 수정

src/main/java/dnd/donworry/controller/UserController.java, src/main/java/dnd/donworry/domain/dto/user/UserResponseDto.java, src/main/java/dnd/donworry/service/UserService.java, src/main/java/dnd/donworry/service/impl/UserServiceImpl.java
현재 로그인 되어 있는 유저의 정보를 response로 반환 하는 API를 개발하였습니다
=>  [FEAT] 유저 정보 조회 API 개발

src/main/java/dnd/donworry/controller/OauthController.java
action의 application-kakao의 redirect url을 기존 로컬 환경에서 vercel로 변경
=> [REFACTOR] 카카오 redirect-Url 프론트 vercel로 action 변경
